name: Ollama Setup in Gitpod

on:
  workflow_dispatch:  # Allows manual triggering
  push:
    branches: [ main ]
    paths:
      - 'setup_ollama.sh'

jobs:
  setup-ollama:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Gitpod CLI
        run: |
          curl -L https://gitpod.io/static/bin/gitpod-cli-linux-amd64 -o gitpod
          chmod +x gitpod
          sudo mv gitpod /usr/local/bin/

      - name: Login to Gitpod
        env:
          GITPOD_TOKEN: ${{ secrets.GITPOD_TOKEN }}
        run: |
          gitpod login --token="$GITPOD_TOKEN"

      - name: Start Gitpod Workspace
        run: |
          echo "Creating workspace..."
          gitpod workspace create "https://github.com/${{ github.repository }}" || true
          echo "Listing workspaces..."
          gitpod workspace list
          # Get only the first (most recent) workspace ID
          workspace_id=$(gitpod workspace list | grep "${{ github.repository }}" | head -n 1 | awk '{print $1}')
          echo "Workspace ID: $workspace_id"
          workspace_url="https://gitpod.io/#$workspace_id"
          echo "Workspace URL: $workspace_url"
          echo "WORKSPACE_URL=$workspace_url" >> $GITHUB_ENV

      - name: Wait for Workspace to be Ready
        run: |
          gitpod workspace wait ${{ env.WORKSPACE_URL }}

      - name: Execute Setup Script
        run: |
          gitpod workspace exec ${{ env.WORKSPACE_URL }} "./setup_ollama.sh"